config/routes.rb
Rails.application.routes.draw do
  devise_for :members

  resources :members, only: [] do
    get :dashboard, on: :member
  end

  resources :albums do
    resources :images
  end

  resources :groups

  root 'home#site_index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :member
  has_many :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :member
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :album


  has_attached_file :album_image,
    storage: :s3,
    s3_credentials: {
      access_key_id: ENV["aws_access_key_id"],
      secret_access_key: ENV["aws_secret_access_key"],
      bucket: "geo-album-image-#{Rails.env}"
    },
    s3_region: "us-west-2",
    path: "image/:attachment/:id/:style/:filename",
    url: ":s3_domain_url",
    styles: { 
      small: "100x100#",
      feed: "500"
     },
    default_url: "400x400.png"

  validates_attachment_content_type :album_image, content_type: /\Aimage\/.*\Z/
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :albums
  has_many :groups
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums_created = current_member.albums
  end
  
  def new
    @album = current_member.albums.new
  end

  def show
    @album = Album.find(params[:id]) 
    @images = @album.images
  end

  def create 
    @album = current_member.albums.create(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def album_params
    params.require(:album).permit(:name, :member_id )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def show
    @group = Group.find(params[:id])
  end


  def new
    @group = current_member.groups.new
  end

  def create
     @group = current_member.groups.create(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :member_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def site_index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_action :set_album
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def new
    @image = @album.images.new
  end

  def create
    @image = @album.images.create(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to album_path(@album), notice: 'Image was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end


  private
  def set_album
    @album = Album.find(params[:album_id])
  end

  def set_image
    @image = Image.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:album_id, :title, 
      :date_taken, :album_image
    )
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/index.html.erb
<div>
  <% @albums_created.each do |album| %>
    <%= album.name %>
    <%= link_to "View Album", album_path(album) %>
  <% end %>
</div>

app/views/albums/new.html.erb
<h1>Yay, create a new album!</h1>

<div>

  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2>Uh oh! See below for errors!</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @album do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "Create Album" %>
  <% end %>
</div>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>

<p><%= link_to "Add Image", new_album_image_path(@album) %></p>

<div>
  <% @images.each do |image| %>
    <p><%= image.title %></p>
    <p><%= image.date_taken %></p>
    <%= image_tag(image.album_image(:medium)) %>
  <% end %>
</div>

app/views/groups/new.html.erb
<h1>Create A New Group!</h1>

<div>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>Uh oh!  See below for errors!</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @group do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <%= f.submit "Create group" %>
  <% end %>
</div>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>

app/views/home/site_index.html.erb
<h1>Welcome to the Pic App</h1>

<p><%= link_to('Share photos now!', new_member_registration_path) %></p> 

app/views/images/new.html.erb
<div>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2>Uh oh!  See below for errors!</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for [@album, @image] do |f| %>
    <%= f.file_field :album_image %>
    <%= f.text_field :title %>
    <%= f.text_field :date_taken %>
    <%= f.submit "Add Image" %>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if member_signed_in? %>
      <p><%= link_to('Sign out', destroy_member_session_path, method: :delete) %></p>
      <p><%= link_to('Dashboard', dashboard_member_path(current_member)) %></p>
      <p><%= link_to('Settings', edit_member_registration_path(current_member)) %></p>
    <% else %>
      <p><%= link_to('Sign in', new_member_session_path) %></p>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/members/dashboard.html.erb
<h1>My Dashboard</h1>

<p><%= link_to "Create New Album", new_album_path %></p>
<p><%= link_to "View Albums", albums_path %></p>
<p><%= link_to "Create New Group", new_group_path %></p>